---
- hosts: hubs
  tags: docker
  name: Install Docker
  roles:
    - geerlingguy.docker
  become: yes

- hosts: hubs
  vars_prompt:
    - name: "ssl_cert_email"
      prompt: "Email for LetsEncrypt SSL Cert Registration?"
      private: no
      confirm: yes
    - name: "ssl_cert_domain"
      prompt: "Domain Name for LetsEncrypts SSL Cert?"
      private: no
      confirm: yes
  roles:
    - common
